### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by sefinehtesfa34** [bisrat-walle/AAU-Cross-Campus-Meal-System#1]
You are doing well bisrate wale. 
Approach:
->Import cv2.
->Import decode function from pyzbar.
->Take the image from the user or scan the image and take image.
->Decode that image using pyzbar.
->Locate the barcode in the given Image.
->Print the data and type of image.
->Display located barcode.

**Comment by bisrat-walle** [comment]
Thanks
